#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

D1_DATABASE="${D1_DATABASE:-DB}"
RECOVERY_DIR="${RECOVERY_DIR:-.scratch/recovery}"
RECOVERY_PHRASE="RECOVER TWO-FACTOR ACCESS"
MODE="local"
TEMP_FILES=()
TEMP_FILE=""
RECOVERY_REFERENCE=""
RESTORE_COMMAND=""

on_exit() {
  local status=$? file
  if (( ${#TEMP_FILES[@]} > 0 )); then
    for file in "${TEMP_FILES[@]}"; do
      rm -f -- "$file"
    done
  fi
  if (( status != 0 )) && [[ -n "$RECOVERY_REFERENCE" ]]; then
    printf '  Recovery point retained: %s\n' "$RECOVERY_REFERENCE" >&2
    printf '  Restore command: %s\n' "$RESTORE_COMMAND" >&2
  fi
  return "$status"
}
trap on_exit EXIT
trap 'exit 129' HUP
trap 'exit 130' INT
trap 'exit 143' TERM

make_temp() {
  TEMP_FILE=$(mktemp)
  chmod 600 "$TEMP_FILE"
  TEMP_FILES+=("$TEMP_FILE")
}

ask_fresh() {
  local key="$1" prompt="$2" input=""
  printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  read -r input || true
  printf -v "$key" '%s' "$input"
}

sql_literal() {
  local value="$1"
  value=${value//\'/\'\'}
  printf "'%s'" "$value"
}

shell_literal() {
  local value="$1"
  value=${value//\'/\'\\\'\'}
  printf "'%s'" "$value"
}

schema_sql() {
  cat <<'SQL'
SELECT CASE WHEN
  EXISTS (SELECT 1 FROM pragma_table_info('user') WHERE name = 'two_factor_enabled')
  AND EXISTS (SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'two_factor')
  AND EXISTS (SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'verification')
  AND EXISTS (SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'session')
  AND EXISTS (SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'account')
  AND EXISTS (SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'oauth_refresh_token')
  AND EXISTS (SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'oauth_access_token')
THEN 1 ELSE 0 END AS schema_ready;
SQL
}

locate_sql() {
  local email
  email=$(sql_literal "$1")
  cat <<SQL
SELECT
  id,
  name,
  email,
  CASE
    WHEN instr(',' || replace(coalesce(role, ''), ' ', '') || ',', ',admin,') > 0
      THEN 'Administrator'
    ELSE 'Standard'
  END AS role,
  CASE
    WHEN EXISTS (
      SELECT 1
      FROM account
      WHERE account.user_id = user.id
        AND account.provider_id = 'credential'
        AND account.password IS NOT NULL
    ) THEN 'Yes'
    ELSE 'No'
  END AS local_password,
  CASE WHEN coalesce(two_factor_enabled, 0) = 1 THEN 'Enabled' ELSE 'Disabled' END AS two_factor
FROM user
WHERE lower(email) = lower($email);
SQL
}

impact_sql() {
  local account_id
  account_id=$(sql_literal "$1")
  cat <<SQL
SELECT
  (SELECT count(*) FROM two_factor WHERE user_id = $account_id) AS two_factor_records,
  (
    SELECT count(*)
    FROM verification
    WHERE identifier GLOB '2fa-*'
      AND identifier NOT GLOB '2fa-attempts-*'
      AND value = $account_id
  ) AS pending_challenges,
  (
    SELECT count(*)
    FROM verification
    WHERE identifier IN (
      SELECT '2fa-attempts-' || identifier
      FROM verification
      WHERE identifier GLOB '2fa-*'
        AND identifier NOT GLOB '2fa-attempts-*'
        AND value = $account_id
    )
  ) AS challenge_attempts,
  (
    SELECT count(*)
    FROM verification
    WHERE identifier GLOB 'trust-device-*'
      AND value = $account_id
  ) AS trusted_devices,
  (SELECT count(*) FROM session WHERE user_id = $account_id) AS sessions,
  (
    SELECT count(*)
    FROM session
    WHERE user_id = $account_id
      AND expires_at > cast(unixepoch('subsecond') * 1000 AS integer)
  ) AS active_sessions,
  (SELECT count(*) FROM oauth_refresh_token WHERE user_id = $account_id) AS oauth_refresh_tokens,
  (SELECT count(*) FROM oauth_access_token WHERE user_id = $account_id) AS oauth_access_tokens;
SQL
}

recovery_sql() {
  local account_id
  account_id=$(sql_literal "$1")
  cat <<SQL
-- Easy Auth operations-only Two-Factor Authentication recovery.
-- The immutable User ID below is the complete mutation boundary.
UPDATE user
SET two_factor_enabled = 0
WHERE id = $account_id;

DELETE FROM verification
WHERE identifier IN (
  SELECT '2fa-attempts-' || identifier
  FROM verification
  WHERE identifier GLOB '2fa-*'
    AND identifier NOT GLOB '2fa-attempts-*'
    AND value = $account_id
);

DELETE FROM verification
WHERE identifier GLOB '2fa-*'
  AND identifier NOT GLOB '2fa-attempts-*'
  AND value = $account_id;

DELETE FROM verification
WHERE identifier GLOB 'trust-device-*'
  AND value = $account_id;

DELETE FROM two_factor
WHERE user_id = $account_id;

DELETE FROM oauth_access_token
WHERE user_id = $account_id;

DELETE FROM oauth_refresh_token
WHERE user_id = $account_id;

DELETE FROM session
WHERE user_id = $account_id;
SQL
}

verify_sql() {
  local account_id
  account_id=$(sql_literal "$1")
  cat <<SQL
SELECT
  (SELECT count(*) FROM user WHERE id = $account_id) AS account_records,
  (SELECT coalesce(two_factor_enabled, 0) FROM user WHERE id = $account_id) AS two_factor_enabled,
  (SELECT count(*) FROM two_factor WHERE user_id = $account_id) AS two_factor_records,
  (
    SELECT count(*)
    FROM verification
    WHERE identifier GLOB '2fa-*'
      AND identifier NOT GLOB '2fa-attempts-*'
      AND value = $account_id
  ) AS pending_challenges,
  (
    SELECT count(*)
    FROM verification
    WHERE identifier IN (
      SELECT '2fa-attempts-' || identifier
      FROM verification
      WHERE identifier GLOB '2fa-*'
        AND identifier NOT GLOB '2fa-attempts-*'
        AND value = $account_id
    )
  ) AS challenge_attempts,
  (
    SELECT count(*)
    FROM verification
    WHERE identifier GLOB 'trust-device-*'
      AND value = $account_id
  ) AS trusted_devices,
  (SELECT count(*) FROM session WHERE user_id = $account_id) AS sessions,
  (SELECT count(*) FROM oauth_refresh_token WHERE user_id = $account_id) AS oauth_refresh_tokens,
  (SELECT count(*) FROM oauth_access_token WHERE user_id = $account_id) AS oauth_access_tokens;
SQL
}

json_rows_count() {
  bun -e '
    const payload = JSON.parse(await Bun.file(process.argv[1]).text());
    const entries = Array.isArray(payload) ? payload : [payload];
    console.log(entries.flatMap((entry) => entry.results ?? []).length);
  ' "$1"
}

json_field() {
  bun -e '
    const payload = JSON.parse(await Bun.file(process.argv[1]).text());
    const entries = Array.isArray(payload) ? payload : [payload];
    const row = entries.flatMap((entry) => entry.results ?? [])[0];
    if (!row || !(process.argv[2] in row)) process.exit(1);
    process.stdout.write(String(row[process.argv[2]] ?? ""));
  ' "$1" "$2"
}

json_display_field() {
  bun -e '
    const payload = JSON.parse(await Bun.file(process.argv[1]).text());
    const entries = Array.isArray(payload) ? payload : [payload];
    const row = entries.flatMap((entry) => entry.results ?? [])[0];
    if (!row || !(process.argv[2] in row)) process.exit(1);
    process.stdout.write(JSON.stringify(String(row[process.argv[2]] ?? "")));
  ' "$1" "$2"
}

print_wrangler_identity() {
  bun -e '
    const identity = JSON.parse(await Bun.file(process.argv[1]).text());
    console.log(`  Authentication type: ${JSON.stringify(String(identity.authType ?? "Unknown"))}`);
    if (identity.email) console.log(`  Authenticated email: ${JSON.stringify(String(identity.email))}`);
    const accounts = Array.isArray(identity.accounts) ? identity.accounts : [];
    console.log("  Available Cloudflare Accounts:");
    for (const account of accounts) {
      console.log(`    - ${JSON.stringify(String(account.name ?? "Unknown"))} (${JSON.stringify(String(account.id ?? "Unknown"))})`);
    }
  ' "$1"
}

has_wrangler_account() {
  bun -e '
    const identity = JSON.parse(await Bun.file(process.argv[1]).text());
    const accounts = Array.isArray(identity.accounts) ? identity.accounts : [];
    process.exit(accounts.some((account) => account.id === process.argv[2]) ? 0 : 1);
  ' "$1" "$2"
}

json_bookmark() {
  bun -e '
    const payload = JSON.parse(await Bun.file(process.argv[1]).text());
    function findBookmark(value) {
      if (!value || typeof value !== "object") return null;
      if (typeof value.bookmark === "string") return value.bookmark;
      for (const child of Object.values(value)) {
        const bookmark = findBookmark(child);
        if (bookmark) return bookmark;
      }
      return null;
    }
    const bookmark = findBookmark(payload);
    if (!bookmark) process.exit(1);
    process.stdout.write(bookmark);
  ' "$1"
}

run_query() {
  local sql="$1" output="$2"
  bunx wrangler d1 execute "$D1_DATABASE" "$MODE_FLAG" --json --command "$sql" > "$output"
}

if [[ "${1:-}" == "--remote" ]]; then
  MODE="remote"
  shift
elif [[ "${1:-}" == "--local" ]]; then
  shift
fi
MODE_FLAG="--$MODE"

case "${1:-}" in
  --print-mode-flag)
    printf '%s\n' "$MODE_FLAG"
    exit 0
    ;;
  --print-locate-sql)
    [[ $# -eq 2 ]] || { printf 'usage: %s [--local|--remote] --print-locate-sql EMAIL\n' "$0" >&2; exit 2; }
    locate_sql "$2"
    exit 0
    ;;
  --print-impact-sql)
    [[ $# -eq 2 ]] || { printf 'usage: %s [--local|--remote] --print-impact-sql USER_ID\n' "$0" >&2; exit 2; }
    impact_sql "$2"
    exit 0
    ;;
  --print-recovery-sql)
    [[ $# -eq 2 ]] || { printf 'usage: %s [--local|--remote] --print-recovery-sql USER_ID\n' "$0" >&2; exit 2; }
    recovery_sql "$2"
    exit 0
    ;;
  --print-verify-sql)
    [[ $# -eq 2 ]] || { printf 'usage: %s [--local|--remote] --print-verify-sql USER_ID\n' "$0" >&2; exit 2; }
    verify_sql "$2"
    exit 0
    ;;
  "") ;;
  *)
    printf 'usage: %s [--local|--remote]\n' "$0" >&2
    exit 2
    ;;
esac

banner "Two-Factor Authentication Recovery"

stage "Preflight"
say "This operations-only procedure removes authentication state after human identity verification."
step "Verify that Bun, Wrangler, and secure temporary-file support are available."
for command_name in bun bunx mktemp; do
  command -v "$command_name" >/dev/null 2>&1 || {
    printf '  %s✗ required command is unavailable:%s %s\n' "$RED" "$RESET" "$command_name" >&2
    exit 1
  }
done
bunx wrangler --version >/dev/null
say "Database mode: $MODE ($MODE_FLAG). Local is the default; remote requires --remote."
if [[ "$MODE" == "remote" ]]; then
  warn "REMOTE mode will permanently revoke credentials in Cloudflare D1."
  confirm "Continue with the explicitly selected remote database?" || {
    say "Stopped before reading or changing the remote database."
    exit 1
  }
  make_temp
  WRANGLER_IDENTITY_OUTPUT="$TEMP_FILE"
  bunx wrangler whoami --json > "$WRANGLER_IDENTITY_OUTPUT"
  print_wrangler_identity "$WRANGLER_IDENTITY_OUTPUT"
  ask_fresh CONFIRMED_CLOUDFLARE_ACCOUNT_ID "Type the intended Cloudflare Account ID:"
  has_wrangler_account "$WRANGLER_IDENTITY_OUTPUT" "$CONFIRMED_CLOUDFLARE_ACCOUNT_ID" || {
    say "That Account ID is not available to the current Wrangler authentication."
    exit 1
  }
  export CLOUDFLARE_ACCOUNT_ID="$CONFIRMED_CLOUDFLARE_ACCOUNT_ID"
  say "Confirmed Cloudflare Account ID: $CONFIRMED_CLOUDFLARE_ACCOUNT_ID"
  say "D1 database name or binding: $D1_DATABASE"
else
  say "Only the local Wrangler D1 database will be used."
fi
confirm "Do you attest that out-of-band human identity verification is complete?" || {
  say "Identity verification is required. No database changes were made."
  exit 1
}
make_temp
SCHEMA_OUTPUT="$TEMP_FILE"
run_query "$(schema_sql)" "$SCHEMA_OUTPUT"
[[ "$(json_field "$SCHEMA_OUTPUT" schema_ready)" == "1" ]] || {
  printf '  The selected D1 database does not have the required 0.5.0 schema. Apply migrations before recovery.\n' >&2
  exit 1
}
say "The selected D1 database has the required recovery schema."

stage "Locate Account"
say "Locate the Account by login email, then bind every later query to its immutable User ID."
ask ACCOUNT_EMAIL "Login email:"
[[ -n "$ACCOUNT_EMAIL" ]] || { printf '  Login email is required.\n' >&2; exit 1; }
make_temp
LOCATE_OUTPUT="$TEMP_FILE"
run_query "$(locate_sql "$ACCOUNT_EMAIL")" "$LOCATE_OUTPUT"
ACCOUNT_COUNT=$(json_rows_count "$LOCATE_OUTPUT")
if [[ "$ACCOUNT_COUNT" != "1" ]]; then
  printf '  Expected exactly one Account, found %s. No database changes were made.\n' "$ACCOUNT_COUNT" >&2
  exit 1
fi
ACCOUNT_ID=$(json_field "$LOCATE_OUTPUT" id)
printf '  %s✓ located%s Account\n' "$GREEN" "$RESET"
printf '  Name: %s\n' "$(json_display_field "$LOCATE_OUTPUT" name)"
printf '  Login email: %s\n' "$(json_display_field "$LOCATE_OUTPUT" email)"
printf '  Immutable User ID: %s\n' "$(json_display_field "$LOCATE_OUTPUT" id)"
printf '  Role: %s\n' "$(json_display_field "$LOCATE_OUTPUT" role)"
printf '  Local password present: %s\n' "$(json_display_field "$LOCATE_OUTPUT" local_password)"
printf '  Two-Factor Authentication: %s\n' "$(json_display_field "$LOCATE_OUTPUT" two_factor)"
confirm "Is this the identity-verified Account?" || {
  say "Stopped before mutation."
  exit 1
}

stage "Impact Preview"
say "Only counts are shown. Secrets, codes, cookies, and token values are never printed."
make_temp
IMPACT_OUTPUT="$TEMP_FILE"
run_query "$(impact_sql "$ACCOUNT_ID")" "$IMPACT_OUTPUT"
printf '  Two-Factor records: %s\n' "$(json_field "$IMPACT_OUTPUT" two_factor_records)"
printf '  Pending challenge records: %s\n' "$(json_field "$IMPACT_OUTPUT" pending_challenges)"
printf '  Challenge-attempt records: %s\n' "$(json_field "$IMPACT_OUTPUT" challenge_attempts)"
printf '  Trusted Device records: %s\n' "$(json_field "$IMPACT_OUTPUT" trusted_devices)"
printf '  Sessions (active / all): %s / %s\n' \
  "$(json_field "$IMPACT_OUTPUT" active_sessions)" \
  "$(json_field "$IMPACT_OUTPUT" sessions)"
printf '  Stored OAuth refresh tokens: %s\n' "$(json_field "$IMPACT_OUTPUT" oauth_refresh_tokens)"
printf '  Stored opaque OAuth access tokens: %s\n' "$(json_field "$IMPACT_OUTPUT" oauth_access_tokens)"
note "The Account, password, Linked Identities/provider tokens, OAuth Clients, Application Authorizations, roles, and activity records are preserved."
confirm "Continue to create a recovery point?" || {
  say "Stopped before mutation."
  exit 1
}

stage "Recovery Point"
if [[ "$MODE" == "local" ]]; then
  mkdir -p "$RECOVERY_DIR"
  chmod 700 "$RECOVERY_DIR"
  BACKUP_FILE="$RECOVERY_DIR/easy-auth-d1-before-2fa-recovery-$(date -u +%Y%m%dT%H%M%SZ)-$$.sql"
  bunx wrangler d1 export "$D1_DATABASE" --local --output "$BACKUP_FILE" -y >/dev/null
  chmod 600 "$BACKUP_FILE"
  RECOVERY_REFERENCE="$BACKUP_FILE"
  RESTORE_COMMAND="bunx wrangler d1 execute $(shell_literal "$D1_DATABASE") --local --file=$(shell_literal "$BACKUP_FILE")"
  say "Local D1 export created: $RECOVERY_REFERENCE"
  warn "The export contains credentials. Keep it private and import it only into an empty local D1 state."
else
  make_temp
  TIME_TRAVEL_OUTPUT="$TEMP_FILE"
  bunx wrangler d1 time-travel info "$D1_DATABASE" --json > "$TIME_TRAVEL_OUTPUT"
  BOOKMARK=$(json_bookmark "$TIME_TRAVEL_OUTPUT")
  RECOVERY_REFERENCE="D1 Time Travel bookmark $BOOKMARK"
  RESTORE_COMMAND="bunx wrangler d1 time-travel restore $(shell_literal "$D1_DATABASE") --bookmark=$(shell_literal "$BOOKMARK")"
  say "$RECOVERY_REFERENCE"
  say "Restore command: $RESTORE_COMMAND"
  warn "Workers Free Tier Time Travel has a seven-day recovery window. Older bookmarks cannot be restored."
fi

stage "Final Confirmation and Execute"
warn "This removes the selected Account's 2FA state, Trusted Devices, Sessions, and stored OAuth credentials."
ask_fresh CONFIRMED_ACCOUNT_ID "Type the full immutable User ID:"
[[ "$CONFIRMED_ACCOUNT_ID" == "$ACCOUNT_ID" ]] || {
  printf '  Immutable User ID did not match. No database changes were made.\n' >&2
  exit 1
}
ask_fresh CONFIRMED_PHRASE "Type $RECOVERY_PHRASE:"
[[ "$CONFIRMED_PHRASE" == "$RECOVERY_PHRASE" ]] || {
  printf '  Recovery phrase did not match. No database changes were made.\n' >&2
  exit 1
}
make_temp
RECOVERY_SQL="$TEMP_FILE"
recovery_sql "$ACCOUNT_ID" > "$RECOVERY_SQL"
bunx wrangler d1 execute "$D1_DATABASE" "$MODE_FLAG" --file "$RECOVERY_SQL" -y >/dev/null
say "The constrained recovery SQL-file execution completed."
note "No application Security activity is written by this operations-only procedure."

stage "Verify"
make_temp
VERIFY_OUTPUT="$TEMP_FILE"
run_query "$(verify_sql "$ACCOUNT_ID")" "$VERIFY_OUTPUT"
for field in \
  two_factor_enabled \
  two_factor_records \
  pending_challenges \
  challenge_attempts \
  trusted_devices \
  sessions \
  oauth_refresh_tokens \
  oauth_access_tokens; do
  [[ "$(json_field "$VERIFY_OUTPUT" "$field")" == "0" ]] || {
    printf '  Verification failed: %s is not zero. Escalate using the recovery reference.\n' "$field" >&2
    exit 1
  }
done
[[ "$(json_field "$VERIFY_OUTPUT" account_records)" == "1" ]] || {
  printf '  Verification failed: the Account record is missing. Escalate immediately.\n' >&2
  exit 1
}
printf '  %s✓ verified%s Two-Factor Authentication is Disabled and selected credentials are absent.\n' "$GREEN" "$RESET"
say "Recovery reference: $RECOVERY_REFERENCE"
say "Restore command: $RESTORE_COMMAND"
say "Next step: the Account signs in with an existing Sign-in Method and may enroll again."
warn "Already delivered ID tokens, stateless artifacts, and relying-party local Sessions cannot be recalled and expire under their own policies."

finish
