/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as DashRouteRouteImport } from './routes/_dash/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashUsersRouteImport } from './routes/_dash/users'
import { Route as DashSessionsRouteImport } from './routes/_dash/sessions'
import { Route as DashProfileRouteImport } from './routes/_dash/profile'
import { Route as DashAuthRouteImport } from './routes/_dash/auth'
import { Route as DashAppsRouteImport } from './routes/_dash/apps'
import { Route as DashAccountsRouteImport } from './routes/_dash/accounts'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const DashRouteRoute = DashRouteRouteImport.update({
  id: '/_dash',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashUsersRoute = DashUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashRouteRoute,
} as any)
const DashSessionsRoute = DashSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => DashRouteRoute,
} as any)
const DashProfileRoute = DashProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashRouteRoute,
} as any)
const DashAuthRoute = DashAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => DashRouteRoute,
} as any)
const DashAppsRoute = DashAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => DashRouteRoute,
} as any)
const DashAccountsRoute = DashAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => DashRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/accounts': typeof DashAccountsRoute
  '/apps': typeof DashAppsRoute
  '/auth': typeof DashAuthRoute
  '/profile': typeof DashProfileRoute
  '/sessions': typeof DashSessionsRoute
  '/users': typeof DashUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/accounts': typeof DashAccountsRoute
  '/apps': typeof DashAppsRoute
  '/auth': typeof DashAuthRoute
  '/profile': typeof DashProfileRoute
  '/sessions': typeof DashSessionsRoute
  '/users': typeof DashUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dash': typeof DashRouteRouteWithChildren
  '/consent': typeof ConsentRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_dash/accounts': typeof DashAccountsRoute
  '/_dash/apps': typeof DashAppsRoute
  '/_dash/auth': typeof DashAuthRoute
  '/_dash/profile': typeof DashProfileRoute
  '/_dash/sessions': typeof DashSessionsRoute
  '/_dash/users': typeof DashUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consent'
    | '/login'
    | '/signup'
    | '/accounts'
    | '/apps'
    | '/auth'
    | '/profile'
    | '/sessions'
    | '/users'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consent'
    | '/login'
    | '/signup'
    | '/accounts'
    | '/apps'
    | '/auth'
    | '/profile'
    | '/sessions'
    | '/users'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_dash'
    | '/consent'
    | '/login'
    | '/signup'
    | '/_dash/accounts'
    | '/_dash/apps'
    | '/_dash/auth'
    | '/_dash/profile'
    | '/_dash/sessions'
    | '/_dash/users'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashRouteRoute: typeof DashRouteRouteWithChildren
  ConsentRoute: typeof ConsentRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash': {
      id: '/_dash'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash/users': {
      id: '/_dash/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof DashUsersRouteImport
      parentRoute: typeof DashRouteRoute
    }
    '/_dash/sessions': {
      id: '/_dash/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof DashSessionsRouteImport
      parentRoute: typeof DashRouteRoute
    }
    '/_dash/profile': {
      id: '/_dash/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashProfileRouteImport
      parentRoute: typeof DashRouteRoute
    }
    '/_dash/auth': {
      id: '/_dash/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof DashAuthRouteImport
      parentRoute: typeof DashRouteRoute
    }
    '/_dash/apps': {
      id: '/_dash/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof DashAppsRouteImport
      parentRoute: typeof DashRouteRoute
    }
    '/_dash/accounts': {
      id: '/_dash/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof DashAccountsRouteImport
      parentRoute: typeof DashRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashRouteRouteChildren {
  DashAccountsRoute: typeof DashAccountsRoute
  DashAppsRoute: typeof DashAppsRoute
  DashAuthRoute: typeof DashAuthRoute
  DashProfileRoute: typeof DashProfileRoute
  DashSessionsRoute: typeof DashSessionsRoute
  DashUsersRoute: typeof DashUsersRoute
}

const DashRouteRouteChildren: DashRouteRouteChildren = {
  DashAccountsRoute: DashAccountsRoute,
  DashAppsRoute: DashAppsRoute,
  DashAuthRoute: DashAuthRoute,
  DashProfileRoute: DashProfileRoute,
  DashSessionsRoute: DashSessionsRoute,
  DashUsersRoute: DashUsersRoute,
}

const DashRouteRouteWithChildren = DashRouteRoute._addFileChildren(
  DashRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashRouteRoute: DashRouteRouteWithChildren,
  ConsentRoute: ConsentRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
